version: "3.8"

services:
  app:
    build: .
    container_name: attend_app
    ports:
      - "8889:8000"
    volumes:
      - ./backend:/app/backend
      - ./public:/app/public
    environment:
      - TELEGRAM_ID=${TELEGRAM_ID}
      - TELEGRAM_ALERT=${TELEGRAM_ALERT}